name: Updated

on:
  workflow_dispatch:

jobs:
  all:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repo
      uses: actions/checkout@v4
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
    # - name: Login to DockerHub
    #   uses: docker/login-action@v3
    #   with:
    #     username: ${{ secrets.DOCKERHUB_USERNAME }}
    #     password: ${{ secrets.DOCKERHUB_TOKEN }}

    # - name: Build and push Docker image
    #   uses: docker/build-push-action@v5
    #   with:
    #     context: .
    #     push: true
    #     tags: gabrielbdornas/${{ github.event.repository.name }}:latest
    #     cache-from: type=registry,ref=gabrielbdornas/${{ github.event.repository.name }}:latest
    #     cache-to: type=inline
    - name: ETL pipeline
      env:
        PROXY_USER: ${{ secrets.PROXY_USER }}
        PROXY_PWD: ${{ secrets.PROXY_PWD }}
      run: docker run --rm --mount type=bind,source=${PWD},target=/project gabrielbdornas/${{ github.event.repository.name }} make all
